export const SITE = {
  website: "https://hi-lei.github.io/",
  author: "Meng Lei",
  profile: "https://www.linkedin.com/in/meng-lei-837a0420/",
  desc: "System architect and software engineer writing about AI inference infrastructure, CLI tooling, terminal UIs, and AI agents.",
  title: "Meng Lei",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: false,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/hi-lei/hi-lei.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Singapore",
} as const;
